all:
  vars:
    ansible_become: true

    ssl_enabled: true
    ssl_mutual_auth_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-172-31-44-31.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-219-2-236.us-west-2.compute.amazonaws.com
    ip-172-31-33-7.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-186-163-190.us-west-2.compute.amazonaws.com
    ip-172-31-34-33.us-west-2.compute.internal:
      ansible_ssh_host: ec2-35-166-39-188.us-west-2.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-172-31-32-149.us-west-2.compute.internal:
      ansible_ssh_host: ec2-52-39-82-173.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-39-82-173.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-39-82-173.us-west-2.compute.amazonaws.com
    ip-172-31-46-230.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-214-106-66.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-214-106-66.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-214-106-66.us-west-2.compute.amazonaws.com
    ip-172-31-33-12.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-222-124-98.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-222-124-98.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-222-124-98.us-west-2.compute.amazonaws.com

schema_registry:
  hosts:
    ip-172-31-45-174.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-202-149-98.us-west-2.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-172-31-35-101.us-west-2.compute.internal:
      ansible_ssh_host: ec2-52-11-136-35.us-west-2.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-172-31-43-194.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-219-69-138.us-west-2.compute.amazonaws.com

ksql:
  hosts:
    ip-172-31-46-49.us-west-2.compute.internal:
      ansible_ssh_host: ec2-35-163-191-168.us-west-2.compute.amazonaws.com
    ip-172-31-40-162.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-202-49-223.us-west-2.compute.amazonaws.com

control_center:
  hosts:
    ip-172-31-38-86.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-209-47-244.us-west-2.compute.amazonaws.com
