all:
  vars:
    ansible_become: true

    ssl_enabled: true
    ssl_mutual_auth_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-172-31-35-219.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-218-234-10.us-west-2.compute.amazonaws.com
    ip-172-31-34-115.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-69-218-197.us-west-2.compute.amazonaws.com
    ip-172-31-33-189.us-west-2.compute.internal:
      ansible_ssh_host: ec2-35-166-236-130.us-west-2.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-172-31-34-106.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-213-198-147.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-213-198-147.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-213-198-147.us-west-2.compute.amazonaws.com
    ip-172-31-43-31.us-west-2.compute.internal:
      ansible_ssh_host: ec2-52-42-154-214.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-42-154-214.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-42-154-214.us-west-2.compute.amazonaws.com
    ip-172-31-43-173.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-212-212-218.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-212-212-218.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-212-212-218.us-west-2.compute.amazonaws.com

schema_registry:
  hosts:
    ip-172-31-47-217.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-213-132-163.us-west-2.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-172-31-46-66.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-210-184-116.us-west-2.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-172-31-44-94.us-west-2.compute.internal:
      ansible_ssh_host: ec2-18-237-70-128.us-west-2.compute.amazonaws.com

ksql:
  hosts:
    ip-172-31-40-108.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-219-135-134.us-west-2.compute.amazonaws.com

control_center:
  hosts:
    ip-172-31-37-79.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-213-243-253.us-west-2.compute.amazonaws.com

