all:
  vars:
    ansible_become: true

    ssl_enabled: true
    ssl_mutual_auth_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-172-31-35-218.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-184-114-210.us-west-2.compute.amazonaws.com
    ip-172-31-43-255.us-west-2.compute.internal:
      ansible_ssh_host: ec2-35-164-217-233.us-west-2.compute.amazonaws.com
    ip-172-31-36-10.us-west-2.compute.internal:
      ansible_ssh_host: ec2-52-10-188-88.us-west-2.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-172-31-46-215.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-221-254-4.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-221-254-4.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-221-254-4.us-west-2.compute.amazonaws.com
    ip-172-31-35-21.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-222-148-181.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-222-148-181.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-222-148-181.us-west-2.compute.amazonaws.com
    ip-172-31-40-251.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-214-104-249.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-214-104-249.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-214-104-249.us-west-2.compute.amazonaws.com

schema_registry:
  hosts:
    ip-172-31-42-198.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-190-197-6.us-west-2.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-172-31-47-153.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-216-145-62.us-west-2.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-172-31-42-66.us-west-2.compute.internal:
      ansible_ssh_host: ec2-52-41-107-26.us-west-2.compute.amazonaws.com

ksql:
  hosts:
    ip-172-31-34-69.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-211-195-159.us-west-2.compute.amazonaws.com

control_center:
  hosts:
    ip-172-31-44-4.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-211-211-146.us-west-2.compute.amazonaws.com

