all:
  vars:
    ansible_become: true

    ssl_enabled: true
    ssl_mutual_auth_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-172-31-38-200.us-west-2.compute.internal:
      ansible_ssh_host: ec2-52-27-113-217.us-west-2.compute.amazonaws.com
    ip-172-31-42-24.us-west-2.compute.internal:
      ansible_ssh_host: ec2-52-33-69-158.us-west-2.compute.amazonaws.com
    ip-172-31-40-245.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-220-204-192.us-west-2.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-172-31-47-162.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-219-162-6.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-219-162-6.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-219-162-6.us-west-2.compute.amazonaws.com
    ip-172-31-45-49.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-187-181-212.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-187-181-212.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-187-181-212.us-west-2.compute.amazonaws.com
    ip-172-31-40-196.us-west-2.compute.internal:
      ansible_ssh_host: ec2-52-36-101-75.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-36-101-75.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-36-101-75.us-west-2.compute.amazonaws.com

schema_registry:
  hosts:
    ip-172-31-42-126.us-west-2.compute.internal:
      ansible_ssh_host: ec2-35-166-5-187.us-west-2.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-172-31-41-129.us-west-2.compute.internal:
      ansible_ssh_host: ec2-35-161-30-45.us-west-2.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-172-31-40-119.us-west-2.compute.internal:
      ansible_ssh_host: ec2-35-167-149-253.us-west-2.compute.amazonaws.com

ksql:
  hosts:
    ip-172-31-45-70.us-west-2.compute.internal:
      ansible_ssh_host: ec2-35-163-225-65.us-west-2.compute.amazonaws.com
    ip-172-31-40-47.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-149-55-83.us-west-2.compute.amazonaws.com

control_center:
  hosts:
    ip-172-31-41-103.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-203-127-117.us-west-2.compute.amazonaws.com

