all:
  vars:
    ansible_become: true

    ssl_enabled: true
    ssl_mutual_auth_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-172-31-43-134.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-217-42-193.us-west-2.compute.amazonaws.com
    ip-172-31-35-103.us-west-2.compute.internal:
      ansible_ssh_host: ec2-35-162-27-173.us-west-2.compute.amazonaws.com
    ip-172-31-44-106.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-216-89-35.us-west-2.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-172-31-40-207.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-219-45-205.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-219-45-205.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-219-45-205.us-west-2.compute.amazonaws.com
    ip-172-31-32-247.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-212-246-224.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-54-212-246-224.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-54-212-246-224.us-west-2.compute.amazonaws.com
    ip-172-31-38-7.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-222-23-125.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-222-23-125.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-222-23-125.us-west-2.compute.amazonaws.com

schema_registry:
  hosts:
    ip-172-31-33-5.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-222-118-42.us-west-2.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-172-31-39-132.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-216-156-27.us-west-2.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-172-31-44-94.us-west-2.compute.internal:
      ansible_ssh_host: ec2-52-39-30-81.us-west-2.compute.amazonaws.com

ksql:
  hosts:
    ip-172-31-34-62.us-west-2.compute.internal:
      ansible_ssh_host: ec2-54-148-16-214.us-west-2.compute.amazonaws.com
    ip-172-31-44-51.us-west-2.compute.internal:
      ansible_ssh_host: ec2-18-236-83-120.us-west-2.compute.amazonaws.com

control_center:
  hosts:
    ip-172-31-35-209.us-west-2.compute.internal:
      ansible_ssh_host: ec2-18-236-167-164.us-west-2.compute.amazonaws.com

